version: '3.3'

services:
  postgres:
    container_name: postgres-service
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  retrieval_service_test:
    container_name: retrieval-service-test
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    environment:
      - HOSTNAME=postgres
    depends_on:
      - postgres
