version: '3.8'

services:
  # postgres:
  #   container_name: postgres-service
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=db
  #   ports:
  #     - "5432:5432"
  #   # volumes:
  #   #   - ./volume_pgsql:/var/lib/postgresql/data

  retrieval_service:
    container_name: retrieval-service
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HOSTNAME=postgres
      - MODEL_URL="https://disk.yandex.ru/d/K7ozxAlGlPanlw"
    ports:
      - "80:8000"
    volumes:
      - ./data:/app/data
    # depends_on:
    #   - postgres