version: '3.8'

services:
  postgres:
    container_name: postgres-service
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      # - LC_ALL=en_US.utf8
      # - LC_COLLATE=en_US.utf8
      # - LC_CTYPE=en_US.utf8
    ports:
      - "5432:5432"
